In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sb
%matplotlib inline 


In [3]:
br=pd.read_csv('Bejaia Region ForestFire Dataset.csv')
af=pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv')

In [4]:
br.head(4)

day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC   DC  ISI  BUI  \
0    1      6  2012           29   57   18    0.0  65.7  3.4  7.6  1.3  3.4   
1    2      6  2012           29   61   13    1.3  64.4  4.1  7.6  1.0  3.9   
2    3      6  2012           26   82   22   13.1  47.1  2.5  7.1  0.3  2.7   
3    4      6  2012           25   89   13    2.5  28.6  1.3  6.9  0.0  1.7   

   FWI    Classes    
0  0.5  not fire     
1  0.4  not fire     
2  0.1  not fire     
3  0.0  not fire

In [5]:








af.head(4)

day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC    DC  ISI  BUI  \
0    1      6  2012           32   71   12    0.7  57.1  2.5   8.2  0.6  2.8   
1    2      6  2012           30   73   13    4.0  55.7  2.7   7.8  0.6  2.9   
2    3      6  2012           29   80   14    2.0  48.7  2.2   7.6  0.3  2.6   
3    4      6  2012           30   64   14    0.0  79.4  5.2  15.4  2.2  5.6   

   FWI    Classes    
0  0.2  not fire     
1  0.2  not fire     
2  0.1  not fire     
3    1  not fire

In [6]:
new_dataset=pd.concat([af , br] ,axis=0 )

In [7]:
new_dataset

day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC    DC  ISI  \
0      1      6  2012           32   71   12    0.7  57.1  2.5   8.2  0.6   
1      2      6  2012           30   73   13    4.0  55.7  2.7   7.8  0.6   
2      3      6  2012           29   80   14    2.0  48.7  2.2   7.6  0.3   
3      4      6  2012           30   64   14    0.0  79.4  5.2  15.4  2.2   
4      5      6  2012           32   60   14    0.2  77.1  6.0  17.6  1.8   
..   ...    ...   ...          ...  ...  ...    ...   ...  ...   ...  ...   
117   26      9  2012           31   54   11    0.0  82.0  6.0  16.3  2.5   
118   27      9  2012           31   66   11    0.0  85.7  8.3  24.9  4.0   
119   28      9  2012           32   47   14    0.7  77.5  7.1   8.8  1.8   
120   29      9  2012           26   80   16    1.8  47.4  2.9   7.7  0.3   
121   30      9  2012           25   78   14    1.4  45.0  1.9   7.5  0.2   

     BUI  FWI    Classes    
0    2.8  0.2  not fire     
1    2.9  0.2  not fire     
2    2.6  0.1  not fire     
3    5.6    1  not fire     
4    6.5  0.9  not fire     
..   ...  ...          ...  
117  6.2  1.7  not fire     
118  9.0  4.1      fire     
119  6.8  0.9  not fire     
120  3.0  0.1  not fire     
121  2.4  0.1  not fire     

[244 rows x 14 columns]

In [8]:
new_dataset.shape

(244, 14)

In [9]:
new_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244 entries, 0 to 121
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   day          244 non-null    int64  
 1   month        244 non-null    int64  
 2   year         244 non-null    int64  
 3   Temperature  244 non-null    int64  
 4    RH          244 non-null    int64  
 5    Ws          244 non-null    int64  
 6   Rain         244 non-null    float64
 7   FFMC         244 non-null    float64
 8   DMC          244 non-null    float64
 9   DC           244 non-null    object 
 10  ISI          244 non-null    float64
 11  BUI          244 non-null    float64
 12  FWI          244 non-null    object 
 13  Classes      243 non-null    object 
dtypes: float64(5), int64(6), object(3)
memory usage: 28.6+ KB


In [10]:
new_dataset.describe()

day       month    year  Temperature          RH          Ws  \
count  244.000000  244.000000   244.0   244.000000  244.000000  244.000000   
mean    15.754098    7.500000  2012.0    32.172131   61.938525   15.504098   
std      8.825059    1.112961     0.0     3.633843   14.884200    2.810178   
min      1.000000    6.000000  2012.0    22.000000   21.000000    6.000000   
25%      8.000000    7.000000  2012.0    30.000000   52.000000   14.000000   
50%     16.000000    7.500000  2012.0    32.000000   63.000000   15.000000   
75%     23.000000    8.000000  2012.0    35.000000   73.250000   17.000000   
max     31.000000    9.000000  2012.0    42.000000   90.000000   29.000000   

            Rain         FFMC         DMC         ISI         BUI  
count  244.000000  244.000000  244.000000  244.000000  244.000000  
mean     0.760656   77.887705   14.673361    4.774180   16.664754  
std      1.999406   14.337571   12.368039    4.175318   14.204824  
min      0.000000   28.600000    0.700000    0.000000    1.100000  
25%      0.000000   72.075000    5.800000    1.400000    6.000000  
50%      0.000000   83.500000   11.300000    3.500000   12.250000  
75%      0.500000   88.300000   20.750000    7.300000   22.525000  
max     16.800000   96.000000   65.900000   19.000000   68.000000

In [11]:
np.mean(new_dataset['day'])

15.754098360655737

In [12]:
new_dataset[new_dataset['day'].isnull()]

Empty DataFrame
Columns: [day, month, year, Temperature,  RH,  Ws, Rain , FFMC, DMC, DC, ISI, BUI, FWI, Classes  ]
Index: []

In [13]:
new_dataset['day'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
117    False
118    False
119    False
120    False
121    False
Name: day, Length: 244, dtype: bool

In [14]:
new_dataset.head(2)

day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC   DC  ISI  BUI  \
0    1      6  2012           32   71   12    0.7  57.1  2.5  8.2  0.6  2.8   
1    2      6  2012           30   73   13    4.0  55.7  2.7  7.8  0.6  2.9   

   FWI    Classes    
0  0.2  not fire     
1  0.2  not fire

In [15]:
new_dataset['day'].sum()

3844

In [16]:
new_dataset['day'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
      dtype=int64)

In [17]:
new_dataset['month'].unique()

array([6, 7, 8, 9], dtype=int64)

In [18]:
new_dataset['year'].unique()

array([2012], dtype=int64)

In [19]:
new_dataset['Temperature'].unique()

array([32, 30, 29, 35, 28, 27, 31, 33, 34, 36, 37, 38, 39, 40, 42, 26, 24,
       25, 22], dtype=int64)

In [20]:
new_dataset.head(2)

day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC   DC  ISI  BUI  \
0    1      6  2012           32   71   12    0.7  57.1  2.5  8.2  0.6  2.8   
1    2      6  2012           30   73   13    4.0  55.7  2.7  7.8  0.6  2.9   

   FWI    Classes    
0  0.2  not fire     
1  0.2  not fire

In [21]:
new_dataset.head(2)

day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC   DC  ISI  BUI  \
0    1      6  2012           32   71   12    0.7  57.1  2.5  8.2  0.6  2.8   
1    2      6  2012           30   73   13    4.0  55.7  2.7  7.8  0.6  2.9   

   FWI    Classes    
0  0.2  not fire     
1  0.2  not fire

In [22]:
new_dataset.isnull().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        1
dtype: int64

In [31]:
# now check which row the dataset has null values
new_dataset[new_dataset['Classes  '].isnull()]

day  month  year  Temperature   RH   Ws  Rain   FFMC   DMC      DC   ISI  \
43   14      7  2012           37   37   18    0.2  88.9  12.9  14.6 9  12.5   

     BUI      FWI Classes    
43  10.4  fire          NaN

In [37]:
# there is only one so, we can drop this 
new_dataset.drop(new_dataset.index[43] ,inplace=True)

In [39]:
new_dataset[new_dataset['Classes  '].isnull()]

Empty DataFrame
Columns: [day, month, year, Temperature,  RH,  Ws, Rain , FFMC, DMC, DC, ISI, BUI, FWI, Classes  ]
Index: []

In [38]:
new_dataset.shape

(242, 14)

In [25]:
new_dataset['Rain '].unique()

array([ 0.7,  4. ,  2. ,  0. ,  0.2,  0.1,  1.3,  0.4,  4.7,  8.7,  4.5,
        1.1,  0.8,  0.6,  1.7,  2.2,  0.3,  0.5,  6. ,  1.9,  3.8,  2.9,
        1.2,  3.1,  4.1,  6.5,  4.4, 13.1,  2.5,  1. ,  1.4, 16.8,  7.2,
       10.1,  0.9,  1.8,  4.6,  8.3,  5.8])

In [41]:
br.shape

(122, 14)

In [47]:
# now make a classification such that for Bejaia region we will assign 0 
# for Algerian forest we will assign 1
 
new_dataset.loc[ : 122 ,'region']=0
new_dataset.loc[122 : , 'region']=1
df=new_dataset

KeyError: 122

In [45]:
new_dataset.shape

(242, 14)

In [48]:
new_dataset

day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC    DC  ISI  \
0      1      6  2012           32   71   12    0.7  57.1  2.5   8.2  0.6   
1      2      6  2012           30   73   13    4.0  55.7  2.7   7.8  0.6   
2      3      6  2012           29   80   14    2.0  48.7  2.2   7.6  0.3   
3      4      6  2012           30   64   14    0.0  79.4  5.2  15.4  2.2   
4      5      6  2012           32   60   14    0.2  77.1  6.0  17.6  1.8   
..   ...    ...   ...          ...  ...  ...    ...   ...  ...   ...  ...   
117   26      9  2012           31   54   11    0.0  82.0  6.0  16.3  2.5   
118   27      9  2012           31   66   11    0.0  85.7  8.3  24.9  4.0   
119   28      9  2012           32   47   14    0.7  77.5  7.1   8.8  1.8   
120   29      9  2012           26   80   16    1.8  47.4  2.9   7.7  0.3   
121   30      9  2012           25   78   14    1.4  45.0  1.9   7.5  0.2   

     BUI  FWI    Classes    
0    2.8  0.2  not fire     
1    2.9  0.2  not fire     
2    2.6  0.1  not fire     
3    5.6    1  not fire     
4    6.5  0.9  not fire     
..   ...  ...          ...  
117  6.2  1.7  not fire     
118  9.0  4.1      fire     
119  6.8  0.9  not fire     
120  3.0  0.1  not fire     
121  2.4  0.1  not fire     

[242 rows x 14 columns]

In [50]:
new_dataset = new_dataset.reset_index(drop=True)  # Ensure numeric index
new_dataset.loc[:122, 'region'] = 0
new_dataset.loc[122:, 'region'] = 1

df=new_dataset



In [51]:
df

day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC    DC  ISI  \
0      1      6  2012           32   71   12    0.7  57.1  2.5   8.2  0.6   
1      2      6  2012           30   73   13    4.0  55.7  2.7   7.8  0.6   
2      3      6  2012           29   80   14    2.0  48.7  2.2   7.6  0.3   
3      4      6  2012           30   64   14    0.0  79.4  5.2  15.4  2.2   
4      5      6  2012           32   60   14    0.2  77.1  6.0  17.6  1.8   
..   ...    ...   ...          ...  ...  ...    ...   ...  ...   ...  ...   
237   26      9  2012           31   54   11    0.0  82.0  6.0  16.3  2.5   
238   27      9  2012           31   66   11    0.0  85.7  8.3  24.9  4.0   
239   28      9  2012           32   47   14    0.7  77.5  7.1   8.8  1.8   
240   29      9  2012           26   80   16    1.8  47.4  2.9   7.7  0.3   
241   30      9  2012           25   78   14    1.4  45.0  1.9   7.5  0.2   

     BUI  FWI    Classes    region  
0    2.8  0.2  not fire        0.0  
1    2.9  0.2  not fire        0.0  
2    2.6  0.1  not fire        0.0  
3    5.6    1  not fire        0.0  
4    6.5  0.9  not fire        0.0  
..   ...  ...          ...     ...  
237  6.2  1.7  not fire        1.0  
238  9.0  4.1      fire        1.0  
239  6.8  0.9  not fire        1.0  
240  3.0  0.1  not fire        1.0  
241  2.4  0.1  not fire        1.0  

[242 rows x 15 columns]

In [52]:
print(new_dataset.index)


RangeIndex(start=0, stop=242, step=1)


In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   day          242 non-null    int64  
 1   month        242 non-null    int64  
 2   year         242 non-null    int64  
 3   Temperature  242 non-null    int64  
 4    RH          242 non-null    int64  
 5    Ws          242 non-null    int64  
 6   Rain         242 non-null    float64
 7   FFMC         242 non-null    float64
 8   DMC          242 non-null    float64
 9   DC           242 non-null    object 
 10  ISI          242 non-null    float64
 11  BUI          242 non-null    float64
 12  FWI          242 non-null    object 
 13  Classes      242 non-null    object 
 14  region       242 non-null    float64
dtypes: float64(6), int64(6), object(3)
memory usage: 28.5+ KB


In [54]:
df['region']=df['region'].astype(int)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   day          242 non-null    int64  
 1   month        242 non-null    int64  
 2   year         242 non-null    int64  
 3   Temperature  242 non-null    int64  
 4    RH          242 non-null    int64  
 5    Ws          242 non-null    int64  
 6   Rain         242 non-null    float64
 7   FFMC         242 non-null    float64
 8   DMC          242 non-null    float64
 9   DC           242 non-null    object 
 10  ISI          242 non-null    float64
 11  BUI          242 non-null    float64
 12  FWI          242 non-null    object 
 13  Classes      242 non-null    object 
 14  region       242 non-null    int32  
dtypes: float64(5), int32(1), int64(6), object(3)
memory usage: 27.5+ KB
